export const CLEAR_STORE = 'CLEAR STORE';

export const TIMEZONES_ACTIONS = {
  'SELECTED TIME ZONE ': 'SELECTED TIME ZONE',
  'CURRENT TIME ZONE': 'CURRENT TIME ZONE',
  'CURRENT IMAGE': 'CURRENT IMAGE',
};
